version: "3"
services:
  develop:
    build: .
    ports:
      - "3000:3000"
    container_name: dataset
    env_file:
      - dev.env
    environment:
      PORT: 3000
      NODE_PATH: app/src
      CT_REGISTER_MODE: auto
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      API_VERSION: v1
      MONGO_PORT_27017_TCP_ADDR: mongo
      FASTLY_ENABLED: "false"
    command: develop
    depends_on:
      - mongo
    volumes:
      - ./app:/opt/dataset/app

  mongo:
    image: mongo:3.4
    container_name: dataset-mongo-develop
    command: --smallfiles
    ports:
      - "27017"
    volumes:
      - $HOME/docker/data/dataset:/data/db
    restart: always
