version: "3"
services:
  develop:
    build: .
    ports:
      - "3001:3001"
    container_name: dataset
    env_file:
      - dev.env
    environment:
      PORT: 3001
      NODE_PATH: app/src
      GATEWAY_URL: http://mymachine:9000
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      MONGO_PORT_27017_TCP_ADDR: mongo
      FASTLY_ENABLED: "false"
    command: develop
    depends_on:
      - mongo
    volumes:
      - ./app:/opt/dataset/app

  mongo:
    image: mongo:3.4
    container_name: dataset-mongo-develop
    command: --smallfiles
    ports:
      - "27020:27017"
    volumes:
      - $HOME/docker/data/dataset/mongodb:/data/db
    restart: always
