develop:
  extends:
    file: base.yml
    service: base
  environment:
    CT_REGISTER_MODE: auto
    CT_URL: http://mymachine:9000
    LOCAL_URL: http://mymachine:3000
    CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
    API_VERSION: v1
    S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
    S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
    STAMPERY_TOKEN: ${STAMPERY_TOKEN}
  command: develop
  links:
    - mongo
  volumes:
    - ./app:/opt/dataset/app
  extra_hosts:
    - "mymachine:$MYMACHINE"
mongo:
  image: mongo:3.4
  container_name: dataset-mongo-develop
  command: --smallfiles
  ports:
    - "27017"
  volumes:
    - $HOME/docker/data/dataset:/data/db
  restart: always
